spring.application.name=eureka-server

# Puerto por defecto de eureka
server.port=8761

# Sirve para que el cliente de eureka no seacliente de si mismo
eureka.client.register-with-eureka=false

# Indica que este cliente no deberia fetchear info del server eureka
eureka.client.fetch-registry=false