spring.application.name=msvc_items

spring.cloud.discovery.client.simple.instances.products-msvc[0].uri=http://localhost:8001
spring.cloud.discovery.client.simple.instances.products-msvc[1].uri=http://localhost:8002